### ISSUE TITLE
Enable TLS on ampache.org

### ISSUE THREAD

**Issue by bentley** [ampache/ampache.github.io#11]
Visiting https://ampache.org/ leads to a certificate error, as GitHub serves a certificate only valid for GitHub subdomains.

As of last year, GitHub supports TLS for custom domains by hosting sites on a CDN. This means [updating the DNS records for ampache.org](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/#configuring-your-domain) should be enough to enable TLS via Let’s Encrypt.

**Comment by cheese1** [comment]
ssl errors on https://www.ampache.org
cert only valid for github...

**Comment by lachlan-00** [comment]
@vollmerk is the only person with dns access

**Comment by lachlan-00** [comment]
yay, it's finally done!
