### ISSUE TITLE
idea: Latest thoughts/recent comments on index page

### ISSUE THREAD

**Issue by Psy-Virus** [ampache/ampache.github.io#7]
Hey ho,
I don't know how the Ampache website is hosted or how complex it could be (or how complex it would be to bring my idea on the screen), but: Would it be possible to make a box or a line at the bottom of the browser window, where visitors can input small comments (160 signs or less) or thoughts about Ampache that are displayed in random order on different positions on the index with some kind of alpha blending or in a speaking bubble?

As dummy comments for the beginning, Github comments could be copied and pasted into some kind of sql flatfile... :thought_balloon:

**Comment by Afterster** [comment]
This is static github pages, no dynamic content possible and I don't want ampache.org to be dependent from any other third party service (github is enough! :smile:). But thanks for the proposal.

**Comment by Psy-Virus** [comment]
Ahh okay, understood!
Thanks for the explanation. :smiley:
